---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: centos7
    image: pycontribs/centos:7
    pre_build_image: true
  - name: centos8
    image: picontribs/centos:8
    pre_build_image: true
  - name: ubuntu
    image: picontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
